-- CREATE TABLE DETECTOR
-- (
--   ID                      INTEGER primary key AUTO_INCREMENT,
--   IP                      VARCHAR(15)  unique not null,
--   ADDRESS                 VARCHAR(50)  not null,
--   SERIAL_NUMBER           VARCHAR(30)  unique not null,
--   START_DATE              DATE         not null,
--   WARRANTY_PERIOD         INTEGER      not null
-- );
-- CREATE TABLE DETECTOR_DATA
-- (
--   ID                      INTEGER primary key AUTO_INCREMENT,
--   DETECTOR_ID             INTEGER      not null,
--   WORK_TIME               DOUBLE      not null,
--   ALL_WORK_TIME           DOUBLE      not null,
--   EMERGENCY_POWER_TIME    DOUBLE      not null,
--   DETECTED_COUNT          INTEGER       not null,
--   POSITIVE_DETECTED_COUNT INTEGER       not null,
--   FREQUENCY               DOUBLE       not null,
--   DATE                    DATE         not null,
--   ERRORS                  VARCHAR(255) not null
-- );
drop table IF EXISTS itpark.authentication_token
create table itpark.authentication_token (token varchar(255) not null, user_id bigint not null, primary key (token))
create table IF NOT EXISTS itpark.chat_message (id bigint generated by default as identity, content varchar(255), created timestamp, status integer, author_id bigint, room_id bigint, primary key (id))
drop table IF EXISTS itpark.registration_token
create table itpark.registration_token (token varchar(255) not null, created timestamp, user_id bigint, primary key (token))
create table IF NOT EXISTS itpark.chat_room (id bigint generated by default as identity, icon varchar(255), name varchar(255), creator_id bigint  not null, primary key (id))
create table IF NOT EXISTS itpark.chat_room_member (id bigint generated by default as identity, icon varchar(255), chat_user_id bigint, primary key (id))
create table IF NOT EXISTS itpark.chat_room_member_rooms (member_entity_id bigint not null, rooms_id bigint not null)
create table IF NOT EXISTS itpark.chat_room_members (room_entity_id bigint not null, members_id bigint not null)
create table IF NOT EXISTS itpark.chat_user (id bigint generated by default as identity, account_non_expired boolean not null, account_non_locked boolean not null, credentials_non_expired boolean not null, enabled boolean not null, name varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id))