POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "username": "username",
  "password": null
}

###

POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "username": "u3@mail.ru",
  "password": "password"
}

###

GET http://localhost:8080/api/registration/confirmation?token=03de88de-627f-499a-b2b2-611db20dcc9d
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("auth_token", response.body.authenticationToken)
});
%}

###

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "u3@mail.ru",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("authenticationToken", response.body.authenticationToken)
});
%}

###
GET http://localhost:8080/api/rooms
Accept: application/json
X-Chat-Token: 2db1b4c4-5abb-4782-a064-80ac82935979

###
POST http://localhost:8080/api/rooms
Content-Type: application/json
X-Chat-Token: eb00a7e7-d4ef-4fb7-8a6b-d0e446c4f7cb

{
  "name": "chat#3",
  "members": [
    "mailfrreg1@mail.ru", "mailfrreg@mail.ru"
  ]
}

###